; Alimentador Pet - firmware ESP32
;
; Gravar pela primeira vez (cabo USB):
;   pio run -t upload
; Depois disso, pela rede (sem cabo):
;   pio run -t upload --upload-port alimentador.local

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    waspinator/AccelStepper@^1.64
    bogde/HX711@^0.7.5
    adafruit/RTClib@^2.1.4
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.4

build_flags =
    -D CORE_DEBUG_LEVEL=3

; grava pela rede: use com --upload-port alimentador.local
[env:esp32dev-ota]
extends = env:esp32dev
upload_protocol = espota
